name: PR Tests

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: Run tests
      run: |
        set +e  # Don't exit immediately on test failure
        dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory TestResults --logger "console;verbosity=detailed"
        TEST_EXIT_CODE=$?
        set -e  # Re-enable exit on error
        
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ $TEST_EXIT_CODE -eq 0 ]; then
          echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some tests failed!" >> $GITHUB_STEP_SUMMARY
        fi
        
        exit $TEST_EXIT_CODE
      
    - name: Generate test report
      if: always()
      run: |
        echo "## Detailed Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Test results have been generated in TRX format and are available as artifacts." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Count test results if the test run completed
        if [ -f "TestResults/test-results.trx" ]; then
          echo "### Test Execution Details:" >> $GITHUB_STEP_SUMMARY
          echo "- Total Tests: $(grep -o '<UnitTestResult' TestResults/test-results.trx | wc -l)" >> $GITHUB_STEP_SUMMARY
          echo "- Passed: $(grep -o 'outcome="Passed"' TestResults/test-results.trx | wc -l)" >> $GITHUB_STEP_SUMMARY
          echo "- Failed: $(grep -o 'outcome="Failed"' TestResults/test-results.trx | wc -l)" >> $GITHUB_STEP_SUMMARY
          echo "- Skipped: $(grep -o 'outcome="NotExecuted"' TestResults/test-results.trx | wc -l)" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/
        retention-days: 7
